# Generated by Django 3.0.7 on 2021-07-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank code')),
            ],
            options={
                'db_table': 'banks',
            },
        ),
    ]
