# Generated by Django 3.0.7 on 2021-07-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bankCode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank code'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bankName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank name'),
        ),
    ]
