# Generated by Django 3.0.7 on 2021-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
