# Generated by Django 3.0.7 on 2021-07-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankAccountName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('accountNo', models.IntegerField(blank=True, null=True, verbose_name='Account Number')),
                ('totalBalance', models.IntegerField(blank=True, null=True, verbose_name='Balance')),
                ('depositAmout', models.IntegerField(blank=True, null=True)),
                ('withrawalAmount', models.IntegerField(blank=True, null=True)),
                ('overdraftLimit', models.IntegerField(blank=True, null=True)),
                ('accounttype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.AccountType')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Branch')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bankaccounts',
            },
        ),
    ]
